### ISSUE TITLE
Deprecated api 

### ISSUE THREAD

**Issue by praveen12bnitt** [konnected-io/noonlight-hass#3]
I get the below deprecation notice from HA.

`SwitchDevice is deprecated, modify NoonlightSwitch to extend SwitchEntity`

Before they fully remove it, lets modify it.

**Comment by mojotaker** [comment]
Yeah, Im getting that warning too.

**Comment by 0n3man** [comment]
I just looked at the code and it contains the recommended fix from HA team for this specific issue.  Can anyone that was seeing this error verify they are no longer seeing the issue?  I'm looking to use this integration and I'd like to verify it's function before signing up for my noonlight account.

**Comment by mojotaker** [comment]
@0n3man I just checked my logs, Im no longer seeing the warning. So code changes might have been made. I have not been looking closely at my system for a while. But if no one else is getting the warning, then yeah this issue can be closed.

**Comment by 0n3man** [comment]
If you don't mind saying have you been satisfied utilizing noonlight for the monitoring via this integration?  Thanks

**Comment by mojotaker** [comment]
@0n3man, I have been very satisfied. As a service, they are very good.  You get a text message from them instantly when your alarm gets tripped, and you get a phone call from them within the first 30 secs of the alarm going off.

They have great integrations with the popular smart devices out there. E.g. you can ask Alexa to get help.

As a company, they reached out to me a couple of times to ask for feedback. The conversations were very personal, that is for e.g I spoke/chatted with a cofounder, and it was a great discussion. I informed them of some things I would like improved, and they did go out of their way to consider and implement them.

I have since been to busy to play around with my home automation system,  but the thing That I saw missing from the HA integration (saw comments in the source code) is the ability to report to noonlight what device and type of alarm that went off. E.g. is it fire/gas vs window/door break-in.

**Comment by 0n3man** [comment]
Thanks for the feedback.  I'm going to see if I can expand the code to add alarm type.  It looks like noonlight will now accept an address as an alternative to gps data.  The konnected integration uses a noonlight library, so hopefully information can be passed through this code in the alert.  Hopefully I can make some progress.  If the developer from Konnected reaches out that would be very helpful.  Once again thanks for the feedback.

**Comment by mojotaker** [comment]
> 
> 
> Thanks for the feedback. I'm going to see if I can expand the code to add alarm type. It looks like noonlight will now accept an address as an alternative to gps data. The konnected integration uses a noonlight library, so hopefully information can be passed through this code in the alert. Hopefully I can make some progress. If the developer from Konnected reaches out that would be very helpful. Once again thanks for the feedback.

Please please please go ahead. This would be a wonderful addition to HA. I don't know how to say, just this alone would make HA more than 50% more valuable and powerful, and will entice more people to sign up for noonlight. Thanks in advance. I can also help with testing.

**Comment by 0n3man** [comment]
mojotaker just wanted to let you know I did a pull request that updates the code so that the alert to noonlight provides your house address, enables the inclusion of the desired  emergency service and allows you to provide a cause to for the alarm to noonlight.   Hopefully the request will be accepted.

**Comment by snicker** [comment]
closing, this was fixed in e5870b4a002
